---
- hosts: all
  become: false

  tasks:
    - name: show the user
      debug:
        var: ansible_user

    - name: get free disk space
      shell:
        cmd: df -h
      register: df
    - name: show free disk space
      debug: var=df
