---
- hosts: all
  become: true

  tasks:
    - name: show some vars
      debug:
        msg: "On {{ ansible_facts['distribution'] }} the user is {{ ansible_user }}"

    - name: get free disk space
      shell:
        cmd: df -h
      register: df
      changed_when: false

    - name: show free disk space
      debug: var=df.stdout_lines

    - name: update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: install dependencies
      apt:
        name: '{{ item }}'
        state: latest
      with_items:
        - nginx

    - name: copy test.html
      template:
        src: test.html.j2
        dest: /var/www/html/test.html

    - name: clone the toydeploy repo
      become: false
      git:
        repo: 'https://github.com/davewsmith/toydeploy.git'
        dest: 'toydeploy'
        depth: 1
      when: ansible_user != 'vagrant'
