---
- hosts: all
  become: true

  vars:
    github_account: davewsmith
    app_name: toydeploy
    app_dir: '/home/{{ ansible_user }}/{{ app_name }}'

  tasks:

    - name: show all facts
      debug:
        var: ansible_facts
      when: false

    - name: show who we are and what we're on
      debug:
        msg: "{{ ansible_user }}@{{ ansible_facts.hostname }} on {{ ansible_facts.lsb.description }}"

    - name: get free disk space
      shell:
        cmd: df -h
      register: df
      changed_when: false

    - name: show free disk space
      debug: var=df.stdout_lines

    - name: update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: install dependencies
      apt:
        name: '{{ item }}'
        state: latest
      with_items:
        - nginx
        - python3-pip
        - python-virtualenv

    - name: copy test.html
      template:
        src: test.html.j2
        dest: /var/www/html/test.html

    - name: clone the repo
      become: false
      git:
        repo: 'https://github.com/{{ github_account }}/{{ app_name }}.git'
        dest: '{{ app_name }}'
        depth: 1

    - name: install app requirements
      become: false
      pip:
        # venv is in .gitignore
        virtualenv: '{{ app_dir }}/venv'
        virtualenv_python: python3
        requirements: '{{ app_dir }}/requirements.txt'
