---
- hosts: all
  become: true

  tasks:
    - name: show the user
      debug:
        var: ansible_user

    - name: get free disk space
      shell:
        cmd: df -h
      register: df
    - name: show free disk space
      debug: var=df.stdout_lines

    - name: install nginx
      apt:
        name: nginx
        state: latest
        update_cache: true

    - name: copy test.html
      template:
        src: test.html.j2
        dest: /var/www/html/test.html
