name: Lint the playbooks

on:
  push:
    branches:
    - master
    paths:
    - '__provision__/ansible/playbooks/**.yml'
  pull_request:
    branches:
    - master
    paths:
    - '__provision__/ansible/playbooks/**.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint
    - name: ansible-lint
      run: |
        cd __provision__/ansible
        ansible-lint playbooks
