name: Test the application

on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md
    - NOTES.md
    - '__provision__'
  pull_request:
    branches:
    - main
    paths-ignore:
    - README.md
    - NOTES.md
    - '__provision__'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Flake8
      run: |
        flake8 . --count --statistics
    - name: Run tests
      run: |
        pytest
